export interface Equipment {
    equipmentId: string,
    name: string,
    internalId: string,
    status: string,
    statusDescription: string,
    version: any,
    hasInRevision: string,
    modelId:string,
    modelName: string,
    shortDescription: string,
    templateId: string,
    subclass: string,
    modelTemplate: string,
    location: string,
    criticalityCode: any,
    criticalityDescription: any,
    manufacturer: string,
    completeness: any,
    createdOn: number,
    changedOn: number,
    publishedO:number,
    serialNumber: any,
    batchNumber: any,
    tagNumber: any,
    lifeCycle: string,
    lifeCycleDescription: string,
    source: string,
    imageURL: string,
    operator: string,
    coordinates: any,
    installationDate: number,
    equipmentStatus: any,
    buildDate: any,
    isOperatorValid: string,
    modelVersion: any,
    soldTo: any,
    image: any,
    consume: string,
    dealer: any,
    serviceProvider: any,
    primaryExternalId: any,
    equipmentSearchTerms: any,
    sourceSearchTerms: string,
    manufacturerSearchTerms: string,
    operatorSearchTerms: string,
    class: string
}

export interface Part {
        id: string,
        sparepartName: string,
        manufacturerPartNumber: string,
        sparepartDescription: string,
        subClass: string,
        eanNumber:string ,
        source:string,
        manufacturer: string,
        unitOfMeasure: string,
        preview: string,
        sourceSearchTerms: string,
        manufacturerSearchTerms: string
        isSourceActive: number,
        isManufacturerActive: number,
        subClassID: string,
        commissioningQuantity: string,
        initialQuantity: string,
        operationQuantity: string,
        quantity: string,
        advisedStockQuantity: string,
        noOfInstructions: string,
        noOfVEDocs: string,
        sparepartInternalID: string,
        sparepartSearchTerms: any,
        bomQuantity: string,
        operatingStatus: string,
        operatingStatusDescription: string,
        canBeOrdered: string,
        orderURL:string ,
        additionalInfo: any,
        baseSiteID: string,
        webRoot: string,
        sourceID: string,
        manufacturerID: string,
        baselineID: string
}

export interface IndicatorValue {
    categoryID: string,
    propertyId: string,
    indicatorGroupName: string,
    indicatorName:string,
    indicatorGroupDesc: string,
    objectId: string,
    indicatorSource: string,
    aggUpdatedTimestamp: any,
    indicatorCategory: string,
    colorCode: any,
    thresholdDescription: any,
    convertedAggregatedValue: any,
    trend: any,
    dataType: string,
    indicatorType: string,
    convertedUOMDesc: any,
    UOM: string,
    convertedUOM: string,
    indicatorDesc: string,
    indicatorColorCode: string,
    isFavorite:string,
    UOMDescription:string,
    Dimension: string,
    DimensionDesc: string,
    uomdescription: string,
    dimension: string,
    dimensionDesc: string,
    pstid: string,
    uom: string
}

export interface WorkOrder {
    TechnicalObjectDescription: string,
    MaintenancePlannerGroup: string,
    ConcatenatedActiveSystStsName: string,
    CreationTime: string,
    __metadata: any,
    MaintenancePlant: string,
    TechnicalObjectLabel: string,
    MaintenanceOrderType:string,
    MaintenancePlanningPlant:string,
    MaintPriorityDesc: string,
    WorkCenter: string,
    AuthorizationGroup: string,
    CreatedByUser: string,
    CreationDate: string,
    MaintenanceOrderInternalID: string,
    ResponsibleCostCenter: string,
    TechObjIsEquipOrFuncnlLoc: string,
    MaintenanceOrder: string,
    TechObjIsEquipOrFuncnlLocDesc: string,
    MaintenanceOrderCategory: string,
    MaintPriority: string,
    ControllingArea: string,
    WorkCenterText: string,
    OrderTypeName: string,
    TechnicalObject: string,
    MaintenanceOrderDesc: string
}