import { WorkOrder } from '../../../models/ecopetrol.model';
export const data = {
    general: {
        "equipmentId": "DB37BA44EBC9476890CDB1304A46C9AD",
        "name": "Model_1902_2ndApril-Equipment",
        "internalId": "Model_1902_2ndApril-Equipment",
        "status": "3",
        "statusDescription": "In Revision",
        "version": 2.0,
        "hasInRevision": "1",
        "modelId": "6D6861F7561540E19BC6A588AB853861",
        "modelName": "Model_1902_2ndApril",
        "shortDescription": "Model_1902_2ndApril-Equipmenta",
        "templateId": "6DAD07501AA3ED8A16008C06E004EFFC",
        "subclass": "measuring_instrument_flow_volume",
        "modelTemplate": "coriolis_mass_flow_transmitter",
        "location": "VIB_TEST_UelWgZiu5G",
        "criticalityCode": null,
        "criticalityDescription": null,
        "manufacturer": "Pumps Ltd",
        "completeness": 87.0,
        "createdOn": 1554336000000,
        "changedOn": 1589500800000,
        "publishedOn": 1554249600000,
        "serialNumber": null,
        "batchNumber": null,
        "tagNumber": null,
        "lifeCycle": "9",
        "lifeCycleDescription": "Not Operational",
        "source": "DCA Manu",
        "imageURL": "3DC79573482040FF9A7C9F7EF09CF36B",
        "operator": "DCA Manu",
        "coordinates": null,
        "installationDate": 1554163200000,
        "equipmentStatus": null,
        "buildDate": null,
        "isOperatorValid": "true",
        "modelVersion": 0.0,
        "soldTo": null,
        "image": null,
        "consume": "1",
        "dealer": null,
        "serviceProvider": null,
        "primaryExternalId": null,
        "equipmentSearchTerms": null,
        "sourceSearchTerms": "[SAAS TENANT]DCA Manufacturer,DCA Manu",
        "manufacturerSearchTerms": "Pumps Ltd",
        "operatorSearchTerms": "[SAAS TENANT]DCA Manufacturer,DCA Manu",
        "class": "process_measurement_technology"
    },
    workorders: [
        {
            "TechnicalObjectDescription": "Equipo para inspección 1",
            "MaintenancePlannerGroup": "910",
            "ConcatenatedActiveSystStsName": "LIB. KKMP NLIQ PREC",
            "CreationTime": "PT10H21M53S",
            "__metadata": {
                "id": "https://vhsals4hci.realtech.es:50000/sap/opu/odata/sap/EAM_OBJPG_TECHNICALOBJECT_SRV/C_TechObjMaintenanceOrder(MaintenanceOrderInternalID='OR000004000117',MaintenanceOrder='4000117')",
                "uri": "https://vhsals4hci.realtech.es:50000/sap/opu/odata/sap/EAM_OBJPG_TECHNICALOBJECT_SRV/C_TechObjMaintenanceOrder(MaintenanceOrderInternalID='OR000004000117',MaintenanceOrder='4000117')",
                "type": "EAM_OBJPG_TECHNICALOBJECT_SRV.C_TechObjMaintenanceOrderType"
            },
            "MaintenancePlant": "",
            "TechnicalObjectLabel": "10000411",
            "MaintenanceOrderType": "YBA1",
            "MaintenancePlanningPlant": "1010",
            "MaintPriorityDesc": "",
            "WorkCenter": "MECH-00",
            "AuthorizationGroup": "",
            "CreatedByUser": "MHERRERA",
            "CreationDate": "/Date(1581897600000)/",
            "MaintenanceOrderInternalID": "OR000004000117",
            "ResponsibleCostCenter": "11300",
            "TechObjIsEquipOrFuncnlLoc": "EAMS_EQUI",
            "MaintenanceOrder": "4000117",
            "TechObjIsEquipOrFuncnlLocDesc": "Equipo",
            "MaintenanceOrderCategory": "30",
            "MaintPriority": "",
            "ControllingArea": "A000",
            "WorkCenterText": "",
            "OrderTypeName": "Mantenimiento correctivo",
            "TechnicalObject": "10000411",
            "MaintenanceOrderDesc": "Prueba inspeccion 01"
        },
        {
            "TechnicalObjectDescription": "Equipo para inspección 1",
            "MaintenancePlannerGroup": "910",
            "ConcatenatedActiveSystStsName": "LIB. KKMP NLIQ PREC",
            "CreationTime": "PT10H21M53S",
            "__metadata": {
                "id": "https://vhsals4hci.realtech.es:50000/sap/opu/odata/sap/EAM_OBJPG_TECHNICALOBJECT_SRV/C_TechObjMaintenanceOrder(MaintenanceOrderInternalID='OR000004000117',MaintenanceOrder='4000117')",
                "uri": "https://vhsals4hci.realtech.es:50000/sap/opu/odata/sap/EAM_OBJPG_TECHNICALOBJECT_SRV/C_TechObjMaintenanceOrder(MaintenanceOrderInternalID='OR000004000117',MaintenanceOrder='4000117')",
                "type": "EAM_OBJPG_TECHNICALOBJECT_SRV.C_TechObjMaintenanceOrderType"
            },
            "MaintenancePlant": "",
            "TechnicalObjectLabel": "10000411",
            "MaintenanceOrderType": "YBA1",
            "MaintenancePlanningPlant": "1010",
            "MaintPriorityDesc": "",
            "WorkCenter": "MECH-00",
            "AuthorizationGroup": "",
            "CreatedByUser": "MHERRERA",
            "CreationDate": "/Date(1581897600000)/",
            "MaintenanceOrderInternalID": "OR000004000117",
            "ResponsibleCostCenter": "11300",
            "TechObjIsEquipOrFuncnlLoc": "EAMS_EQUI",
            "MaintenanceOrder": "4000117",
            "TechObjIsEquipOrFuncnlLocDesc": "Equipo",
            "MaintenanceOrderCategory": "30",
            "MaintPriority": "",
            "ControllingArea": "A000",
            "WorkCenterText": "",
            "OrderTypeName": "Mantenimiento correctivo",
            "TechnicalObject": "10000411",
            "MaintenanceOrderDesc": "Prueba inspeccion 01"
        },
        {
            "TechnicalObjectDescription": "Equipo para inspección 1",
            "MaintenancePlannerGroup": "910",
            "ConcatenatedActiveSystStsName": "LIB. KKMP NLIQ PREC",
            "CreationTime": "PT10H21M53S",
            "__metadata": {
                "id": "https://vhsals4hci.realtech.es:50000/sap/opu/odata/sap/EAM_OBJPG_TECHNICALOBJECT_SRV/C_TechObjMaintenanceOrder(MaintenanceOrderInternalID='OR000004000117',MaintenanceOrder='4000117')",
                "uri": "https://vhsals4hci.realtech.es:50000/sap/opu/odata/sap/EAM_OBJPG_TECHNICALOBJECT_SRV/C_TechObjMaintenanceOrder(MaintenanceOrderInternalID='OR000004000117',MaintenanceOrder='4000117')",
                "type": "EAM_OBJPG_TECHNICALOBJECT_SRV.C_TechObjMaintenanceOrderType"
            },
            "MaintenancePlant": "",
            "TechnicalObjectLabel": "10000411",
            "MaintenanceOrderType": "YBA1",
            "MaintenancePlanningPlant": "1010",
            "MaintPriorityDesc": "",
            "WorkCenter": "MECH-00",
            "AuthorizationGroup": "",
            "CreatedByUser": "MHERRERA",
            "CreationDate": "/Date(1581897600000)/",
            "MaintenanceOrderInternalID": "OR000004000117",
            "ResponsibleCostCenter": "11300",
            "TechObjIsEquipOrFuncnlLoc": "EAMS_EQUI",
            "MaintenanceOrder": "4000117",
            "TechObjIsEquipOrFuncnlLocDesc": "Equipo",
            "MaintenanceOrderCategory": "30",
            "MaintPriority": "",
            "ControllingArea": "A000",
            "WorkCenterText": "",
            "OrderTypeName": "Mantenimiento correctivo",
            "TechnicalObject": "10000411",
            "MaintenanceOrderDesc": "Prueba inspeccion 01"
        }
    ]
};
