export const data = [
  {
      "id": "54D2AB833A334B35A5469A69C8773857",
      "sparepartName": "spr11",
      "manufacturerPartNumber": "232esf",
      "sparepartDescription": "desc1111",
      "subClass": null,
      "eanNumber": "",
      "source": "DCA Manu",
      "manufacturer": "PEPPERL+FUCHS",
      "unitOfMeasure": "Acre",
      "preview": "",
      "sourceSearchTerms": "[SAAS TENANT]DCA Manufacturer,DCA Manu",
      "manufacturerSearchTerms": "PEPPERL+FUCHS",
      "isSourceActive": 1,
      "isManufacturerActive": 1,
      "subClassID": "",
      "commissioningQuantity": "0",
      "initialQuantity": "0",
      "operationQuantity": "0",
      "quantity": "1",
      "advisedStockQuantity": "1",
      "noOfInstructions": "0",
      "noOfVEDocs": "0",
      "sparepartInternalID": "spr11",
      "sparepartSearchTerms": null,
      "bomQuantity": "1",
      "operatingStatus": "4",
      "operatingStatusDescription": "Released",
      "canBeOrdered": "0",
      "orderURL": "",
      "additionalInfo": null,
      "baseSiteID": "",
      "webRoot": "",
      "sourceID": "2173D4CFBB004A128C5B9C7A49ECF7B0",
      "manufacturerID": "630B75CB67EB426CB9654E4FA7C17EFD",
      "baselineID": "0"
  },
  {
      "id": "1902CCF9616D48A6BD7F2DB9FDBD55E7",
      "sparepartName": "dsadsa22",
      "manufacturerPartNumber": "22sss22dd22",
      "sparepartDescription": "sadASDasd",
      "subClass": "coriolis_mass_flow_transmitter",
      "eanNumber": "",
      "source": "DCA Manu",
      "manufacturer": "Nokia",
      "unitOfMeasure": "Cubic centimeter per second",
      "preview": "",
      "sourceSearchTerms": "[SAAS TENANT]DCA Manufacturer,DCA Manu",
      "manufacturerSearchTerms": "Nokia,Nokia",
      "isSourceActive": 1,
      "isManufacturerActive": 1,
      "subClassID": "6DAD07501AA3ED8A16008C06E004EFFC",
      "commissioningQuantity": "0",
      "initialQuantity": "0",
      "operationQuantity": "0",
      "quantity": "0",
      "advisedStockQuantity": "0",
      "noOfInstructions": "0",
      "noOfVEDocs": "0",
      "sparepartInternalID": "dsadsa22",
      "sparepartSearchTerms": null,
      "bomQuantity": "1",
      "operatingStatus": "4",
      "operatingStatusDescription": "Released",
      "canBeOrdered": "1",
      "orderURL": "https://sap-ain.demo.hybris.com/",
      "additionalInfo": null,
      "baseSiteID": "powertools",
      "webRoot": "yb2bacceleratorstorefront",
      "sourceID": "2173D4CFBB004A128C5B9C7A49ECF7B0",
      "manufacturerID": "559306B56BA5415FBE63DA289828F57B",
      "baselineID": "0"
  },
  {
      "id": "3F012B0D0B0F4E7D889238CB7783EAC7",
      "sparepartName": "SP-lb37jildgu",
      "manufacturerPartNumber": "MPN-lb37jildgu",
      "sparepartDescription": "sparepart_desc_lb37jildgu",
      "subClass": null,
      "eanNumber": "lb37jildgu",
      "source": "DCA Manu",
      "manufacturer": "DCA Manu",
      "unitOfMeasure": "Bar",
      "preview": null,
      "sourceSearchTerms": "[SAAS TENANT]DCA Manufacturer,DCA Manu",
      "manufacturerSearchTerms": "[SAAS TENANT]DCA Manufacturer,DCA Manu",
      "isSourceActive": 1,
      "isManufacturerActive": 1,
      "subClassID": null,
      "commissioningQuantity": "0",
      "initialQuantity": "0",
      "operationQuantity": "0",
      "quantity": "0",
      "advisedStockQuantity": "0",
      "noOfInstructions": "0",
      "noOfVEDocs": "0",
      "sparepartInternalID": "SP-lb37jildgu",
      "sparepartSearchTerms": null,
      "bomQuantity": "1",
      "operatingStatus": "4",
      "operatingStatusDescription": "Released",
      "canBeOrdered": "1",
      "orderURL": "https://gdm-sdciot.demo.hybris.com/",
      "additionalInfo": null,
      "baseSiteID": "powertools",
      "webRoot": "yb2bacceleratorstorefront",
      "sourceID": "2173D4CFBB004A128C5B9C7A49ECF7B0",
      "manufacturerID": "2173D4CFBB004A128C5B9C7A49ECF7B0",
      "baselineID": "0"
  }
];
